---
- name: Install required software
  apt: name={{ item }} state=present
  with_items:
    - mysql-server-5.6
    - python-mysqldb

- name: Create mysql database
  mysql_db: name={{ mysql.db }} state=present

- name: Create mysql user
  mysql_user:
    name={{ mysql.user }}
    password={{ mysql.password }}
    priv=*.*:ALL
