#!/bin/sh

# chkconfig: - 85 15
# description: start/stop unicorn script.
# processname: unicorn_app

export PATH=/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin

# move to project root directory
NAME='unicorn_rails'
APP_ROOT_DIR="{{ rails.dir }}/current"
PID="$APP_ROOT_DIR/tmp/pids/unicorn.pid"
CONF="$APP_ROOT_DIR/config/unicorn.rb"
ENVIROMENT='production'
USER='root'

start()
{
  if [ -e $PID ]; then
    echo "$NAME already started";
    exit 1;
  fi
  echo "start $NAME";
  cd $APP_ROOT_DIR
  su -c "/usr/local/rbenv/shims/bundle exec unicorn -E $ENVIROMENT -c $CONF -D" $USER
}

stop()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started";
    exit 1;
  fi
  echo "stop $NAME";
  su -c "kill -QUIT `cat ${PID}`" $USER
  su -c "rm -f $PID" $USER
}

force_stop()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started";
    exit 1;
  fi
  echo "stop $NAME";
  su -c "kill -TERM `cat ${PID}`" $USER
  su -c "rm -f $PID" $USER
}

reload()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started";
    start
    exit 0;
  fi
  echo "reload $NAME";
  su -c "kill -HUP `cat ${PID}`" $USER
}

restart()
{
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  force-stop)
    force_stop
    ;;
  reload)
    reload
    ;;
  restart)
    restart
    ;;
  *)
    echo "Syntax Error: release [start|stop|force-stop|reload|restart]"
    ;;
esac

exit

